version: '3.6'

services:
  database:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=123
    ports:
    - 5432:5432
    volumes:
    - db:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  server:
    build:
      context: .
    ports:
      - 65432:65432

volumes:
  redis_data:
  db:

