version: '3.6'

services:
  database:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=123
    volumes:
    - db:/var/lib/postgresql/data


  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  balancer:
    build:
      context: .
    environment:
    - SERVER0_URL=http://server0:65432/
    - SERVER1_URL=http://server1:65432/
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    ports:
    - 65432:65432
    command: ["python", "run_balancer.py"]

  server0:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:123@database:5432/postgres

  server1:
    build:
      context: .
    environment:
    - DATABASE_URL=postgresql://postgres:123@database:5432/postgres


volumes:
  redis_data:
  db:

